[package]
name = "rust_lib_flutter_surrealdb_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"


surrealdb = { version = "2.4.0", features = ["kv-rocksdb"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
serde = "1.0.228"
serde_json = "1.0.145"
