[package]
name = "spooky-stream-processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ulid = "=1.1.0"
anyhow = "1.0"
blake3 = { version = "1.5", default-features = false, features = ["std"] }
regex = "1.12.2"
lazy_static = "1.4"
nom = "7.1.3"
rustc-hash = "2.1.1"
smol_str = { version = "0.3.1", features = ["serde"] }
rayon = { version = "1.8", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mimalloc = "0.1.48"

[dev-dependencies]
rayon = "1.11.0"
ulid = "=1.1.0"
