[package]
name = "spooky-stream-processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nom = "7"
anyhow = "1.0"
blake3 = { version = "1.5", default-features = false, features = ["std"] }
rustc-hash = "2.1.1"
smol_str = { version = "0.2", features = ["serde"] }
mimalloc = { version = "0.1", default-features = false }
simd-json = "0.17.0"
rayon = "1.11.0"
hashbrown = { version = "0.15.2", features = ["serde"] }

[dev-dependencies]
uuid = { version = "1.19.0", features = ["v4"] }
